version: "3.8"

services:
  state-service:
    build:
      context: .
      dockerfile: ../services/state-service/Dockerfile
    volumes:
      - $HOME/.splitup:/app/.splitup
    ports:
      - "${SPLITUP_CONFIG_API_PORT:-8000}:8000"
    working_dir: /app
    environment:
      - HOME=/app
      - SPLITUP_DATA_DIR=/app/.splitup
      - SPLITUP_STATE_SERVICE_NOTIFICATION_URL=${SPLITUP_STATE_SERVICE_NOTIFICATION_URL:-http://localhost:${SPLITUP_COMPUTE_SERVICE_CONFIG_API_PORT:-6068}/notify}
    networks:
      - internal-network

  compute-service:
    build:
      context: .
      dockerfile: ../services/compute-service/Dockerfile
    volumes:
      - $HOME/.splitup:/app/.splitup
    working_dir: /app
    environment:
      - HOME=/app
      - SPLITUP_DATA_DIR=/app/.splitup
      - SPLITUP_COMPUTE_SERVICE_CONFIG_API_PORT=${SPLITUP_COMPUTE_SERVICE_CONFIG_API_PORT:-6068}
      - SPLITUP_LISTENER_SERVICE_API_ENDPOINT=http://localhost:${SPLITUP_LISTENER_SERVICE_PORT:-5058}
      - SPLITUP_STORAGE_API_ENDPOINT=${SPLITUP_STORAGE_API_ENDPOINT}
      - SPLITUP_STORAGE_API_KEY=${SPLITUP_STORAGE_API_KEY}
    networks:
      - internal-network

  listener-service:
    build:
      context: .
      dockerfile: ../services/listener-service/Dockerfile
    working_dir: /app
    environment:
      - SPLITUP_LISTENER_SERVICE_PORT=${SPLITUP_LISTENER_SERVICE_API_PORT:-5058}
      - SPLITUP_CLIENT_SOLANA_PRIVATE_KEY=${SPLITUP_CLIENT_SOLANA_PRIVATE_KEY}
      - SPLITUP_LISTENER_RPC_URL=${SPLITUP_LISTENER_RPC_URL}
    networks:
      - internal-network

  heartbeat-service:
    build:
      context: .
      dockerfile: ../services/heartbeat-service/Dockerfile
    working_dir: /app
    networks:
      - internal-network

networks:
  internal-network:
    driver: bridge
