version: "3.8"

services:
  mock-chain:
    build:
      context: .
      dockerfile: ../services/mock-chain/Dockerfile
    ports:
      - "${SPLITUP_CONFIG_API_PORT:-8000}:8000"
    working_dir: /app
    environment:
      - HOME=/app
      - MOCK_CHAIN_PORT=${MOCK_CHAIN_PORT:-1234}
      - MOCK_CHAIN_HOST=${MOCK_CHAIN_HOST:-localhost}
    networks:
      - internal-network

networks:
  internal-network:
    driver: bridge
